### ISSUE TITLE
Linkind Switch ESP32Solo WS240010008, Rule1 breaks MQT BLE.

### ISSUE THREAD

**Issue by Keribi** [tony-fav/tasmota-blerry#10]
Im Using a Linkind Switch ESP32Solo WS240010008 (thermostat+BLE)  with Blerry 0.1.3 and all was fine until I setup multi-press options to the switch and a Rule1.   I applied the following and restarted the device after each command.  So73 1, So1 1, So32 2, rule1 on button1#state=10 do power1 toggle endon, Rule1 1, Restarted and all BLE MQT activity stopped. Tried several times and same result.

var user_config = {'494208006617': {'alias': 'inkbird', 'model': 'IBSTH2', 'discovery': true},           
                  'A4C1381AF1BC': {'alias': 'govee', 'model': 'GVH5075', 'discovery': true}}

**Comment by tony-fav** [comment]
You probably overwrote the rule that loads blerry...

`rule1 on button1#state=10 do power1 toggle endon on system#boot do br load('blerry.be') endon`

Should work.

**Comment by Keribi** [comment]
Thanks Tony!  Will try.
