### ISSUE TITLE
Moved Blerry to different device now sensors unavailable in HA.

### ISSUE THREAD

**Issue by Keribi** [tony-fav/tasmota-blerry#14]
I had Blerry installed on a Linkind switch with bluetooth but noticed excessive RSSI activity from a Inkbird sensor. I think the activity was too much for the esp32 to handle.  I was getting missed and delayed switch presses as I watched the console. I am no longer using the Linkind switch for BLE.  I am now using a esp32  with esp32-bluetooth installed.  BLE and MQT messages look good but sensor entities show unavailable in HA. What could cause this after switching devices? I am getting the tele from the esp32 temp etc...

**Comment by tony-fav** [comment]
There is nothing special about the troubleshooting steps when switching from one device to the next. In fact, you can have overlapping devices reporting the same sensor, and it should work fine. Please follow the troubleshooting steps in the readme. It is highly likely that blerry error'd upon initialization or the firmware you have put on the device has an error or update that is incompatible with blerry at the moment. Please try the firmware here: https://github.com/tony-fav/tasmota-blerry/blob/dev-trusty-firmware/tested_firmware/tasmota32-ble-berry.bin

**Comment by Keribi** [comment]
Will Try Tony, Thanks

**Comment by tony-fav** [comment]
Please close the issue if successful.

**Comment by Keribi** [comment]
All is fine now Tony. I think I was using the wrong bin on both devices.  Thanks again.
