### ISSUE TITLE
BRY: Exception> 'value_error' - unsupported protocol when running auto setup script

### ISSUE THREAD

**Issue by shampeon** [tony-fav/tasmota-blerry#32]
Running the auto setup script from [the dev README](https://github.com/tony-fav/tasmota-blerry/tree/dev#compatible-esp32) throws the following error:

```
BRY: Exception> 'value_error' - unsupported protocol
stack traceback:
	<native>: in native function
	input:5: in function `start_blerry_setup`
	input:18: in function `main`
```

Firmware: https://github.com/tony-fav/tasmota-blerry/blob/main/tested_firmware/tasmota32solo1-linkind-ble-berry.bin
Device: Linkind 2 button switch, non-dimmer

**Comment by tony-fav** [comment]
Please try the firmware on the dev branch. A requirement for the dev branch's auto setup to run correctly is TLS support and that was not part of the firmware in main. You can still upload files manually if you don't want to flash a new firmware (which is understandable if you've been stable!)

**Comment by tony-fav** [comment]
(if it works, please close the issue)

**Comment by shampeon** [comment]
Ok, confirmed it works with `dev` firmware.

**Comment by Vendo232** [comment]
I have the same issue, where can I download FW which will work with blerry on Linkind 2 button swtich?
