### ISSUE TITLE
CGG1 e-ink display

### ISSUE THREAD

**Issue by greggotcher** [tony-fav/tasmota-blerry#37]
I have a couple of the CGG1 Cleargrass (Qingping): hygro thermometer, round body, e-ink displays.  I know I can get them working using ESP home, but you need a bindkey.  Is this something that can be supported in tasmota-blerry?  What would you need from me to try and get this functioning?

Here is an Amazon link to the device I am talking about: https://www.amazon.com/Qingping-Bluetooth-Thermometer-Hygrometer-Temperature/dp/B08N64HC6B?ref_=ast_sto_dp&th=1&psc=1

This is an awesome project.  Thanks so much.

**Comment by tony-fav** [comment]
I currently have no devices that require a bindkey so no real knowledge of where to start with the decryption. I guess I could try putting an LYWSD03MMC back to stock firmware and try that.

As I was typing this out I realized that sensor you linked can be flashed with the pvvx firmware: https://github.com/pvvx/ATC_MiThermometer <-- this is your best path forward. It eliminates the need for the bindkey and should already be supported by blerry once in that state with the `ATCpvvx` driver.
