### ISSUE TITLE
bindkey

### ISSUE THREAD

**Issue by lucibuz** [tony-fav/tasmota-blerry#44]
I add MCCGQ02HL (Xiaomi Mijia Window Door Sensor 2) but is showing a NO KEY message.
I have the bindkey of the device, how can I add it in the settings?

**Comment by tony-fav** [comment]
That device is not currently supported by blerry. The UI you are seeing is from the built in Tasmota bluetooth support. See [here](https://tasmota.github.io/docs/Bluetooth/#encryption-and-bind_key) for their instructions on setting up bindkeys.
