### ISSUE TITLE
Not getting anything but RSSI for Siwtchbot TH

### ISSUE THREAD

**Issue by edestecd** [tony-fav/tasmota-blerry#47]
I got a new switchbot temperature meter and its on Firmware v2.8.
I'm using the WoSensorTH with no luck. All it shows is RSSI and no Temperature / Humidity or battery.

What info can I provide to help troubleshoot?

**Comment by edestecd** [comment]
Also I have a GVH5075 and ATCpvvx attached as well and they work as expected so I think I have everything setup OK

**Comment by tony-fav** [comment]
The new switchbot sensor is supported on dev branch

**Comment by edestecd** [comment]
It works on the dev branch. I have both the Thermometer and Hygrometer as well as the  Thermometer and Hygrometer Plus working.
