### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by bschatzow** [tony-fav/tasmota-blerry#5]
I watched Travis's video and used the latest blerry files with the edit for my Mac address. I added rule 1, restarted but the files did not compile. I am running it on an esp32 ble device withe the latest tasmota firmware. Any idea on what I am doing wrong?

**Comment by devzwf** [comment]
did you enable rule1 ?

**Comment by bschatzow** [comment]
I missed this step.  It works now.
