### ISSUE TITLE
Curious about Moes Bluetooth Smart Switch Relay

### ISSUE THREAD

**Issue by StuartIanNaylor** [tony-fav/tasmota-blerry#50]
https://www.moeshouse.com/products/bluetooth-smart-switch-relay-module-single-point-control-and-pairing-without-wifi-network-bluetooth-sigmesh-functional-wireless-remote-control-with-bluetooth-gateway

Already Bluetooth Mesh Sig, haven't a clue whats inside or really much tasmota knowledge just noticed more devices seem to be coming online and my curiosity thought what the hell so I got x2.
They are cheap 2x from aliexpress cost me £10 and awaiting for them to arrive and haven't the foggiest how to control them from a Pi but just looking around on a fact finding mission hence why here.

**Comment by tony-fav** [comment]
Bluetooth mesh devices are not supported by blerry. Only BLE advertisement parsing is support and limited ability to do BLE commands both of which are very different than mesh.
