### ISSUE TITLE
Slight change to the readme

### ISSUE THREAD

**Issue by bschatzow** [tony-fav/tasmota-blerry#6]
I missed the rule1 1 and I see others have as well.  I think if you had:
1. Create the following rule: Rule1 ON System#Boot DO br load('blerry.be') ENDON
2. Enable (Rule1 1) 
3. Restart Tasmota (Some of the commands used in blerry.be are not initialized by the time autoexec.be is run. So, you must load blerry.be as part of a rule.)
I missed the rule1 1 and I see that others have as well.  Otherwise the directions and code work very well!  Another excellent video from 
Travis.

**Comment by tony-fav** [comment]
I updated the readme with some troubleshooting tips.
