### ISSUE TITLE
Legacy Support Switchbot Plus (was: BRY: Exception> 'key_error')

### ISSUE THREAD

**Issue by schrej-zz** [tony-fav/tasmota-blerry#64]
Hi;
I tried to read the new [Switchbot Plus](https://www.amazon.com/SwitchBot-Thermometer-Hygrometer-Temperature-Notification-dp-B09QBR7XJD/dp/B09QBR7XJD/ref=dp_ob_title_def?th=1)
with the WOSensorTH driver.
(I'm still on legacy, as I started with it, ran well until now and my tries to get the new blerry SW lead to unresponsive devices)
I get the following errors:

BRY: Exception> 'key_error' - C4C21F0FF871/1
stack traceback:
	<native>: in native function
	<unknown source>: in function `DetailsBLE_callback`
	<unknown source>: in function `try_rule`
	<unknown source>: in function `exec_rules`
	<unknown source>: in function `event`

How can I support to get this device running? I don't expect much changes to the current driver.

**Comment by tony-fav** [comment]
Make sure `C4C21F0FF871/1` is used in your configuration file instead of just `C4C21F0FF871`

**Comment by schrej-zz** [comment]
Thanks for the fast response.
Now I have no exceptions anymore. But the device delivers no values:
"DetailsBLE":{"mac":"C4C21F0FF871/1","a":"BL_Switchbot_01","RSSI":-65,"p":"0201060EFF6909C4C21F0FF8713A0B02964709163DFD698064029647","0xfd3d":"698064029647"}}

**Comment by tony-fav** [comment]
Make sure you use the driver on the dev branch: https://github.com/tony-fav/tasmota-blerry/blob/dev/blerry/drivers/blerry_driver_WoSensorTH.be

**Comment by schrej-zz** [comment]
Thanks,
that's the driver of the new Blerry. I'm still using Legacy.
I think, I have to backport it to legacy to use it there, right?

**Comment by tony-fav** [comment]
Yes you would have to. There is no driver for that device in the legacy offering.

**Comment by tony-fav** [comment]
To be clear, the WoSensorTH is supported by the Plus model is not, on legacy. Both are supported in dev branch

**Comment by schrej-zz** [comment]
OK,
thanks for your support.
For anyone still using support of this device in legacy:
Just replace line in file [blerry_model_WoSensorTH.be](https://github.com/tony-fav/tasmota-blerry/blob/main/blerry-legacy/blerry/blerry_model_WoSensorTH.be)
`      if (adv_type == 0x16) && (adv_len == 9) && (adv_data[0..1] == bytes('000D'))`
by
`      if (adv_type == 0x16) && (adv_len == 9) && ((adv_data[0..1] == bytes('000D')) || (adv_data[0..1] == bytes('3DFD')))`

Works like a charm.

Joerg

**Comment by tony-fav** [comment]
Nice! Thanks! https://github.com/tony-fav/tasmota-blerry/commit/ee7d3c0cf5438d3eb9a987cd9ee42109c6b9dedf
