### ISSUE TITLE
Switchbot W1901400 - BlerryGetConfig returns Command Unknown 

### ISSUE THREAD

**Issue by baylanger** [tony-fav/tasmota-blerry#67]
Hi.

Trying to get blerry configured on W1901400. Like in #57 , I'm using tasmota32c3-bluetooth.bin built in past 24 hours.

When following the doc. to set blerry, it seems to do would it should. I ran it multiple time so the reason it's finding a existing files.
```
Found an existing blerry_config.json
Removing blerry.bec
Found Blerry Load as Part of Rule 1
Blerry Setup Complete
```

But then on the console, running BlerryGetConfig returns:
```
04:32:24.893 MQT: stat/Washer/RESULT = {"Command":"Unknown"}
```

I do not see any driver when looking at the filesystem. I uploaded the WoHand one hoping that would fix it but didn't. I admit I am brand new to tasmota, any help is appreciated.

Thank you!

**Comment by baylanger** [comment]
I noticed a note that newer releases of tasmota might not "work" - I went ahead and installed 12.0.2.2 but still facing the same issue.

**Comment by tony-fav** [comment]
The most likely scenario in this case is that even though the setup script appears to work, it was actually fed a 0 byte blerry.be (and really has no way to check as it's such a small copy+pastable script).

Please check the file system (Manage File System) and confirm. If so, all you should need to do is follow the manual setup instructions to upload the blerry.be manually.

**Comment by baylanger** [comment]
Geez, it is indeed empty. It's a bit late here, will follow the manual instructions and confirm/close this ticket the later tomorrow.

**Comment by baylanger** [comment]
Adding the content to blerry.pe fixed Blerry 🕺 

Then I started seeing the following and upgrading to 12.4.0.2 made this go away.
```
06:26:35.612 BRY: Exception> 'attribute_error' - 'nil' value has no attribute 'attributes'
```

PR #61 says to use 12.0.2.2 , I will monitor the device for any crash/reboot and if happen, I'll add a comment in there.

Thank you.
