### ISSUE TITLE
Feature Request: Add support for HLK-LD2410B

### ISSUE THREAD

**Issue by mochoandre** [tony-fav/tasmota-blerry#68]
Please add Support for HLK-LD2410B presence sensors wich are really cheap and seems to work good.

best regards

**Comment by tony-fav** [comment]
@mochoandre, can you try the `dev` driver and see if it prints out anything interesting in the log. We had someone try the same in digi's discord with no good results. It seems this device requires connecting, which Blerry doesn't support, it's just a listener to adverts.

**Comment by tony-fav** [comment]
Seeing some confirmation of my suspicion here: https://github.com/custom-components/ble_monitor/issues/1010
