### ISSUE TITLE
BRY: failed to load '/blerry_newBLE.be' (syntax_error - /blerry_newBLE.be:40: 'BLE' undeclared (first use in this function))

### ISSUE THREAD

**Issue by evaluationevaluation** [tony-fav/tasmota-blerry#76]
Hi,

I'm just doing my first steps with Berry and Blerry so please forgive me if I ask silly questions.

I managed to flash Tasmota 13.0.0 (Web flasher) to my Esp32Cam module, uploaded Blerry files first by executing the setup script and again manually (because blerry.be was empty).
Files are now present: blerry.be ~31.5k, blerry_newBLE.bs ~3,6k, blerry_config.json with 1 module configured, blerry_driver_Xiaomi.be automatically got downloaded during my tests, rule1 is configured and working).

But I get the error message during load of blerry_newBLE.be stating that BLE() is not defined.

I tried to find a definition of BLE() in the files but did not succeed.
I renamed BLE() to Blerry() as I assumed that this could be a typo in the code. But seemed to be a silly idea. System got extremely slow and got another error stating that Blerry has not atribute named adv_cb. But this attribute is also found nowhere in Blerry code base...

Any idea what is going wrong? Is BLE() a system object provided by Tasmota/Berry or is there a bug somewhere in Blerry?

Thanks a lot for your help
 Eva

**Comment by tony-fav** [comment]
Is there any other problem?

If you are running a build with regular BLE capability, you should not add
the newBLE file. This is for use if you use a firmware with the
"homebridge" or "mibridge" mi32 feature instead of the classic BLE
treatment.

If you delete this file, things should work fine.

**Comment by evaluationevaluation** [comment]
hmm. Saw the last line of blerry.bs with load command for blerry_newBLE.bs and thought that the file then needs to be uploaded before...

Tested around a lot in the meanwhile and after waiting several minutes the Tasmota Stock seems to work fine and send a message with sensor values to my NodeRed instance. What is the advantage of Blerry over this Tasmota stock functionality?
So far I didn't manage to get a message by Blerry...

**Comment by tony-fav** [comment]
It would be required if you were running the homebridge or mibridge
firmwares. Those have different code for interacting with BLE data.

blerry offers more supported devices (it started as an attempt to support
inkbird devices without resorting to esphome lambda functions) and HA MQTT
Discovery. If you only have Xiaomi devices and plan to use nodered, there
may not be much reason to use blerry.

**Comment by evaluationevaluation** [comment]
thank you very much for the explanation!
