### ISSUE TITLE
Mqtt entity name stats with device name, new mqtt requirements 

### ISSUE THREAD

**Issue by IsaacBreuer** [tony-fav/tasmota-blerry#78]
The new nqtts requirements that a entity not to use the device name, it looks like blerry names the device and entities with duplicate name thatxwill stop working soon.
Below is warning I got 

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped off the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue

**Comment by tony-fav** [comment]
Hey @IsaacBreuer thanks for the note, I'll have to look at what the required change from the HA side is. Don't want to do anything that would break anyone's automations.

**Comment by devzwf** [comment]
thanks @tony-fav 
this MQTT naming convention is a pain....

**Comment by tony-fav** [comment]
https://github.com/tony-fav/tasmota-blerry/tree/fixHAMQTTwarning

Can y'all check this really tiny change from this branch that should fix this warning?

**Comment by tony-fav** [comment]
Closed by https://github.com/tony-fav/tasmota-blerry/pull/79
