### ISSUE TITLE
tasmota.publish() is deprecated

### ISSUE THREAD

**Issue by bam80** [tony-fav/tasmota-blerry#83]
https://github.com/tony-fav/tasmota-blerry/blob/ce6c2f05c0d96b8b7dbc0b38166a526e778299d8/blerry/blerry.be#L609

> Deprecated see mqtt.publish

https://tasmota.github.io/docs/Berry/#tasmota-object

**Comment by tony-fav** [comment]
Due to instability of Tasmota BLE, many users (if not all successful users) are still on older versions of Tasmota (11 or 12). So, not necessarily worried about this yet.

**Comment by bam80** [comment]
OK, but maybe keep it open until then?
