### ISSUE TITLE
Sensors to not appear as statistics in HA

### ISSUE THREAD

**Issue by logularjason** [tony-fav/tasmota-blerry#84]
Thanks for this project!

I have been able to configure a govee device, however in HA it does not appear as a statistic (so that I can chart it).

I think this is because the discovery topic lacks a `state_class: measurement` field.

I am new to HA so may be mistaken and would be grateful if there is a work-around.   I have also asked the workaround question on the HA forums [here](https://community.home-assistant.io/t/how-to-supplement-mqtt-discovery-to-add-state-class/722673).

**Comment by tony-fav** [comment]
Hi @logularjason, this has been brought up a couple of times, and the vote in discord seemed to be to not apply this in general to all sensors, but there is a way to override and add the state_class to any particular sensor or sensor type by adding the stat_cla as a discovery override field. 

![image](https://github.com/tony-fav/tasmota-blerry/assets/42725386/4b008bb7-16cc-418d-aad1-ac3cd649d209)

This is also (barely) shown in the documentation https://github.com/tony-fav/tasmota-blerry/tree/dev?tab=readme-ov-file#configuration-json

With these options, the sensors you choose will have those statistics in HA.
